# Generated by Django 4.1 on 2024-06-23 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='quiz_id',
        ),
        migrations.AddField(
            model_name='answers',
            name='choice',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='registerd_english_word_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vocabularies.registered_english_words'),
        ),
        migrations.DeleteModel(
            name='Quizzes',
        ),
    ]
