# Generated by Django 4.1 on 2024-06-23 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vocabularies', '0002_remove_answers_quiz_id_answers_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='quiz_set_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
